### PR TITLE
feat: add ape.tax ftm icons

### PR DESCRIPTION
**Pull request by DarkGhost7**

### CODE REVIEW

**Comment by DarkGhost7** [comment]
Let me know if this is the correct format.

**Comment by DarkGhost7** [comment]
Don't merge yet plz

**Comment by nymmrx** [comment]
> Don't merge yet plz

Converted to a draft

**Comment by DarkGhost7** [comment]
ready to go this is all the ape.tax vaults icons on ftm yvtokens. Let me know if anything else is needed.

**Pull request merged**
